export const GET_LOADING = 'GET_LOADING';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_FAILURE = 'GET_FAILURE';
export const GET_LOADING_ONE_CHARACTER = 'GET_LOADING_ONE_CHARACTER';
export const GET_ONE_CHARACTER_SUCCESS = 'GET_ONE_CHARACTER_SUCCESS';
