export const TODOS_ACTION_TYPES = {
  ADD_TODO: 'ADD_TODO',
  EDIT_TODO: 'EDIT_TODO',
  CANCEL_EDIT: 'CANCEL_EDIT',
  COMPLETE_EDIT: 'COMPLETE_EDIT',
  DELETE_TODO: 'DELETE_TODO',
  IS_EDITING: 'IS_EDITING',
};
