export const GET_ARTISTS_LOADING = "GET_ARTISTS_LOADING";
export const GET_ARTISTS_SUCCESS = "GET_ARTISTS_SUCCESS";
export const GET_ARTISTS_FAILURE = "GET_ARTISTS_FAILURE";

export const GET_ALBUMS_SUCCESS = "GET_ALBUMS_SUCCESS";