export const PROJECTS_ACTION_TYPES = {
  ADD_PROJECT: 'ADD_PROJECT',
  EDIT_PROJECT: 'EDIT_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  LOADING_PROJECTS: 'LOADING_PROJECTS',
  LIST_PROJECTS: 'LIST_PROJECTS',
  GET_ERROR: 'GET_ERROR',
};
